const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const MODEL = process.env.CHAT_MODEL || 'claude-haiku-4-5';

const DEMOS = {
  carpatediem:{"brand":"Carpate Diem","web":"https://carpatediem.sk/nase-vina/","products":["BIO Müller Thurgau 2025, suché","Rizling vlašský 2025, suché","Viechové víno 2025, suché 1 l","Silvánske zelené 2024, suché","BIO Tramín červený 2025, suché","Cuvée Devín & Pálava 2024, suché","Rizling rýnsky 2024 – LIMITED, suché","Rizling vlašský 2023 – LIMITED, suché","Tramín červený BARIQUE 2020, suché","BIO Devín 2024, polosuché","BIO Pálava 2024, polosladké","BIO Tramín červený 2024, polosladké","Frankovka modrá 2024, suché","BIO Nitria 2024 – LIMITED, suché","BIO Hron rosé 2025, suché","Cabernet Sauvignon rosé 2025, polosuché","Saint Laurent rosé 2024","Frizzante Cabernet Sauvignon 2025, polosuché","Frizzante Muškát moravský 2024, polosuché"],"fallback":{"white":"K rybe a ľahkým jedlám je od Carpate Diem dobrý smer BIO Müller Thurgau alebo Rizling vlašský 2025; plnší je Tramín červený BARIQUE. Vo Výbere vína nájdem aj ďalšie.","red":"K mäsu odporúčam limitovanú BIO Nitriu 2024 alebo sviežu Frankovku modrú 2024. Výber vína ešte zohľadní vašu chuť.","sweet":"Ak máte radi sladšie, skúste polosladkú BIO Pálavu 2024, BIO Tramín červený 2024 alebo polosuchý BIO Devín.","gift":"Na darček sa hodí limitovaná edícia — Rizling rýnsky, Rizling vlašský alebo Nitria — či Tramín červený BARIQUE 2020. Vo Výbere vína zohľadníme, čo má obdarovaný rád.","default":"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Carpate Diem na konkrétne víno."}},
  vinkor:{"brand":"Vinárstvo Vinkor","web":"https://vinkor.sk/obchod/","products":["Pálava 2025, polosuché","Sauvignon 2025, suché","Veltlínske zelené 2025, suché","Rizling rýnsky 2024, suché","Chardonnay 2025, suché","Rulandské šedé 2025, suché","Devín 2025, suché","Pálava 2024, suché","Rulandské šedé 2023, polosladké","Devín 2023, polosladký","Pálava 2024, sladká 0,5 l","Veltlínske zelené 2022, ľadové víno, sladké 0,375 l","Cabernet Sauvignon 2022, suché","Dunaj 2024, suché","Cabernet Sauvignon Rosé 2025, suché","Frizzante Rosé 2024, polosuché","Frizzante 2025, suché","To pravé slovenské — Devín a Dunaj v drevenej kazete","Darček Všetko najlepšie! — 3 suché vína v kazete"],"fallback":{"white":"K rybe a ľahkým jedlám je od Vinkoru dobrý smer suchý Sauvignon 2025 alebo Rizling rýnsky 2024; plnší je ocenený Devín 2025. Vo Výbere vína nájdem aj ďalšie.","red":"K mäsu odporúčam Cabernet Sauvignon 2022, šampióna Oenofora, alebo Dunaj 2024 so zlatou z AWC Vienna. Výber vína ešte zohľadní vašu chuť.","sweet":"Ak máte radi sladšie, skúste polosuchú Pálavu 2025, polosladký Devín 2023 alebo ľadové Veltlínske zelené 2022.","gift":"Na darček sa hodí kazeta To pravé slovenské, darček Všetko najlepšie! alebo ľadové víno 0,375 l. Vo Výbere vína zohľadníme, čo má obdarovaný rád.","default":"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinárstva Vinkor na konkrétne víno."}},
  skrobak:{"brand":"Vinařství Škrobák","web":"https://vinoskrobak.cz/internetovy-obchod/","products":["Irsai Oliver 2024, kabinetní, suché","Ryzlink vlašský 2025, pozdní sběr, suché","Ryzlink rýnský 2025, kabinetní, suché","Sylvánské zelené 2024, pozdní sběr, suché","Sauvignon 2023, kabinetní, suché","Hibernal 2025, pozdní sběr, suché","Pálava 2025, pozdní sběr, suché","Rulandské bílé 2023, pozdní sběr, suché","Rulandské šedé 2023, výběr z hroznů, suché","Tramín 2024, pozdní sběr, suché","Tramín 2025, pozdní sběr, polosuché","Aurelius 2022, pozdní sběr, sladké","Solaris 2020, výběr z cibéb, sladké 0,5 l","Ryzlink vlašský / Tramín 2018, ledové, sladké 0,375 l","Frankovka 2018, ledové, sladké 0,375 l","Modrý Portugal 2023, zemské, suché","Frankovka 2021, pozdní sběr, suché","Dornfelder 2025, pozdní sběr, suché","Rulandské modré 2022, pozdní sběr","Alibernet rosé 2025, zemské, polosuché","Frankovka klaret 2023, suché","Frizzante rosé 2023","Muškát moravský Frizzante 2025, polosuché","Blanc de blanc No.1 2022, extra brut"],"fallback":{"white":"K rybe a ľahkým jedlám je od Škrobáka dobrý smer svieži Irsai Oliver alebo Sauvignon 2023; plnšie je Rulandské šedé zo suda. Vo Výbere vína nájdem aj ďalšie.","red":"K mäsu odporúčam Rulandské modré 2022 alebo Dornfelder 2025, ľahší je Modrý Portugal. Výber vína ešte zohľadní vašu chuť.","sweet":"Ak máte radi sladšie, skúste polosuchý Tramín 2025, sladký Aurelius, Solaris z cibéb alebo ľadové víno.","gift":"Na darček sa hodí ľadové víno, Solaris z cibéb alebo sekt Blanc de blanc No.1. Vo Výbere vína zohľadníme, čo má obdarovaný rád.","default":"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Škrobák na konkrétne víno."}},
  skovajsa:{brand:"Víno Skovajsa",web:"https://www.vinoskovajsa.sk/e-shop/",products:["Rizling vlašský FRESH 2025, suché","Silvánske zelené IDENTITY 2024, suché","Pinot blanc IDENTITY 2025, suché","Chardonnay IDENTITY 2025, suché","Devín IDENTITY 2025, suché","Veltlínske zelené TERROIR 2025, suché","Frankovka modrá FRUITY 2023, suché","Neronet IDENTITY 2021, suché","Svätovavrinecké TERROIR 2022, suché","Neronet SELECTION 2022, suché","Chardonnay FRIZZANTE 2025, suché","Cabernet FRIZZANTE 2024, suché (rosé)","SEKT ROSÉ N.V., brut","SEKT BLANC N.V., brut nature"],fallback:{white:"K rybe a ľahkým jedlám je od Skovajsovcov dobrý smer svieži Rizling vlašský FRESH alebo Silvánske zelené IDENTITY; plnšie je Veltlínske zelené TERROIR. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Neronet SELECTION 2022 alebo Svätovavrinecké TERROIR, ľahšia je Frankovka FRUITY 2023. Výber vína ešte zohľadní vašu chuť.",sweet:"Skovajsa robí suché vína. Najovocnejšie pôsobí Devín IDENTITY a perlivé frizzante.",gift:"Na darček sa hodí SEKT BLANC brut nature, Neronet SELECTION alebo Veltlínske zelené TERROIR. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Víno Skovajsa na konkrétne víno."}},
  placek:{brand:"Vinařství Jan Plaček",web:"https://www.vinoplacek.cz/",products:["Hibernal 2025, pozdní sběr, suché","Rulandské šedé 2025, pozdní sběr, suché","Chardonnay 2023, pozdní sběr, Privileg, suché","Rinot 2021, pozdní sběr, suché, zrálo v sudu","Savilon 2025, pozdní sběr, polosuché","Pálava 2025, kabinet, polosuché","Mladé Pokušení 2025, polosladké","Hibernal 2025, pozdní sběr, polosladké","Cabernet Cortis 2025, suché","Zweigeltrebe 2024, pozdní sběr, suché","Cuvée ANAH 2023, pozdní sběr, suché","Frankovka 2023, výběr z hroznů, Oak age, suché","Merlot 2022, výběr z hroznů, Oak age, suché","Cuvée 348 2022, pozdní sběr, Oak age","Rulandské modré rosé 2025, pozdní sběr, polosuché","Cabernet Cortis klaret 2025, výběr z hroznů, polosladké","RosénCO2 2025, perlivé rosé, polosladké","Bublinky 2025, Veltlínské zelené, perlivé","Sekt Plaček brut, Ryzlink rýnský 2022"],fallback:{white:"K rybe a ľahkým jedlám je od Plačeka dobrý smer suchý Hibernal 2025 alebo Rulandské šedé 2025; plnšie je Chardonnay 2023 zo suda. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Cuvée 348 so zlatou medailou alebo Merlot 2022 z radu Oak age, na každý deň Cabernet Cortis. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste polosladké Mladé Pokušení, polosladký Hibernal 2025 alebo perlivé RosénCO2.",gift:"Na darček sa hodí Cuvée 348, Merlot 2022 Oak age alebo Sekt Plaček brut. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Jan Plaček na konkrétne víno."}},
  lipa:{brand:"Víno Lípa",web:"https://vinolipa.cz/",products:["Veltlínské zelené 2025, suché","Veltlínské zelené BETON 2025, suché","Sauvignon 2025, suché","Sylvánské zelené 2025, suché","Donauriesling 2024, suché","Hibernal 2025, suché","Ryzlink vlašský 2024, pozdní sběr, suché","Ryzlink vlašský 2024 (beton), suché","Ryzlink vlašský 2024 (sud), suché","Ryzlink vlašský 2024 (keramika), suché","Ryzlink rýnský 2024, pozdní sběr, suché","Ryzlink rýnský 2024, pozdní sběr, suché","Pálava 2025, polosuché","Rulandské šedé 2025, polosuché","Pálava 2024, výběr z hroznů, polosladké","Pálava 2023, výběr z bobulí, sladké","Cabernet Moravia 2023, výběr z hroznů, suché","Lipasecco Zweigeltrebe rosé 2025, polosuché","Lipasecco cuvée 2025, polosuché","Sekt Chardonnay Brut Nature 2023","Sekt Rulandské modré Extra Brut 2023"],fallback:{white:"K rybe a ľahkým jedlám je od Lípy dobrý smer suchý Veltlínské zelené 2025 alebo Sauvignon 2025; zaujímavý je Ryzlink vlašský v betóne, sude alebo keramike. Vo Výbere vína nájdem aj ďalšie.",red:"Z červených má Víno Lípa Cabernet Moravia 2023 vo výbere z hrozna so striebornou medailou AWC Vienna — k mäsu a grilu.",sweet:"Ak máte radi sladšie, skúste polosladkú Pálavu 2024 alebo sladkú Pálavu 2023 vo výbere z bobúľ.",gift:"Na darček sa hodí limitovaný Sekt Chardonnay Brut Nature, sladká Pálava z bobúľ alebo Ryzlink vlašský z keramiky. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Víno Lípa na konkrétne víno."}},
  pristal:{brand:"Víno Přistál",web:"https://www.znojmo.wine/",products:["Sauvignon Blanc 2025, suché","Hibernal 2025, polosuché","Coupage PINOT 2025, polosuché","Pálava 2025, polosuché","Veltlínské zelené 2024 BETON, suché","Ryzlink rýnský 2023 BETON, suché","Sauvignon Blanc 2022 BETON, suché","Sauvignon Blanc z Kraví hory 2021, akátový sud","Pinot Gris 2021, dubový sud, suché","RED Dornfelder 2024, suché","Frankovka 18, dubový sud, suché","Zweigeltrebe rosé 2025, polosuché","Frizzante Cuvée 2025, polosuché","Pét-nat Veltlínské zelené 2025","Pét-nat Pinot Blanc 2025","Pét-nat Zweigeltrebe rosé 2025"],fallback:{white:"K rybe a ľahkým jedlám je od Přistála dobrý smer suchý Sauvignon Blanc 2025; pre zážitok Veltlínské zelené alebo Ryzlink rýnský z betónového vajca. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Frankovku 18 z dubového suda, ovocnejší je RED Dornfelder 2024. Výber vína ešte zohľadní vašu chuť.",sweet:"Víno Přistál robí suché a polosuché vína. Najjemnejšie pôsobí polosuchá Pálava 2025 alebo Coupage PINOT 2025.",gift:"Na darček sa hodí Frankovka 18 z dubového suda alebo víno z betónového vajca. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Víno Přistál na konkrétne víno."}},
  buchtovi:{brand:"Vinařství Buchtovi",web:"https://www.vinobuchtovi.cz/e-shop",products:["Sauvignon 2024, suché","Ryzlink rýnský 2024, pozdní sběr","Hibernal 2024, pozdní sběr, suché","Muškát moravský, polosuché","Chardonnay 2024, suché","Pálava 2024, kryomacerace, výběr z hroznů, suché","Tramín červený 2024, VOC, polosuché","Rulandské šedé 2024, pozdní sběr, polosladké","Pálava 2024, výběr z hroznů, polosladké","Kerner 2024, výběr z hroznů, sladké","Merlot 2023, suché","Dunaj 2023, výběr z hroznů, suché","Nadzahrady 2023, pozdní sběr","Dornfelder 2022, pozdní sběr, suché","Rulandské modré 2022, pozdní sběr, suché","Cabernet Moravia 2022, suché","Cabernet Moravia rosé 2023, polosuché","Rosé Frizzante 2024, polosladké","Sekt Demi Sec Chardonnay","Sekt Brut Ryzlink rýnský 2023"],fallback:{white:"K rybe a ľahkým jedlám je od Buchtovcov dobrý smer suchý Sauvignon 2024 alebo Hibernal 2024; plnšie je Chardonnay 2024 so zlatou medailou. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Merlot 2023 alebo Dunaj 2023, ovocnejší je Dornfelder 2022. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste sladký Kerner 2024, polosladkú Pálavu 2024 alebo Sekt Demi Sec Chardonnay.",gift:"Na darček sa hodí Pálava z kryomacerácie so zlatými medailami, Merlot 2023 alebo Sekt Brut Ryzlink rýnský. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Buchtovi na konkrétne víno."}},
  vajbar:{brand:"Vinařství Vajbar",web:"https://www.vajbar.cz/e-shop/",products:["Veltlínské zelené 2024, suché","Müller Thurgau 2025, suché","Ryzlink rýnský 2022, suché","Rulandské šedé 2024, suché","Chardonnay 2023, suché","Chardonnay 2021, polosuché","Hibernal 2024, polosuché","Pálava 2024, polosuché","Stařečkovo 2024, suché","Ryzlink vlašský 2010, suché (archivní)","Tramín červený 2023, polosladké","Pálava 2023, polosladké","Frankovka 2020, suché","Svatovavřinecké 2020, suché","Rulandské modré 2020, suché","Cuvée Kamila 2020, rosé, polosuché","Rosé Cuvée 2023, polosladké","Bublinky 2025, perlivé, polosuché","Frizzante Rosé 2025, polosuché","Frizzante Klaret 2025, polosladké"],fallback:{white:"K rybe a ľahkým jedlám je od Vajbarovcov dobrý smer suché Veltlínské zelené 2024 alebo mladý Müller Thurgau 2025; plnšie je Rulandské šedé 2024. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Svatovavřinecké 2020 alebo Rulandské modré 2020 z dubového suda, ľahšia je Frankovka 2020. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste polosladký Tramín červený 2023, Pálavu 2023 alebo Rosé Cuvée 2023 k dezertom.",gift:"Na darček sa hodí archívny Ryzlink vlašský 2010, cuvée Stařečkovo alebo Rulandské modré z dubového suda. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Vajbar na konkrétne víno."}},
  rajnic:{brand:"Víno Rajníc",web:"https://www.vinorajnic.sk/",products:["Rizling vlašský 2025, suché","Rizling rýnsky 2025, suché","Sauvignon blanc 2025, suché","Müller Thurgau 2025, suché","Pálava 2025, suché","3 Pinoty cuvée 2021, suché","Cabernet Sauvignon rosé 2025, suché","Frizzante Cabernet Sauvignon rosé, suché","Frankovka modrá 2021, suché","Pinot Noir 2021, suché","Merlot 2021, suché","Dunaj 2024, suché","Pinot Noir 2015, suché"],fallback:{white:"K rybe a ľahkým jedlám je od Rajníca dobrý smer suchý Rizling vlašský alebo Sauvignon blanc 2025; plnšie je cuvée 3 Pinoty. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Merlot 2021 alebo Dunaj 2024, pre výnimočnú chvíľu vyzretý Pinot Noir 2015. Výber vína ešte zohľadní vašu chuť.",sweet:"Víno Rajníc robí suché vína. Najovocnejšie pôsobí Pálava 2025 a rosé z Cabernetu Sauvignon.",gift:"Na darček sa hodí Pinot Noir 2015 so zlatou medailou z Mondiale des Pinots alebo Merlot 2021. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Víno Rajníc na konkrétne víno."}},
  paulus:{brand:"Vinařství Paulus",web:"https://vinarstvipaulus.cz/eshop/",products:["Ryzlink vlašský 2024, výběr z hroznů, suché","Ryzlink rýnský 2024, pozdní sběr, suché","Sauvignon 2024, pozdní sběr, suché","Kerner 2025, výběr z hroznů, suché","Rulandské šedé 2025, výběr z hroznů, suché","Pálava 2025, pozdní sběr, polosuché","Tramín červený 2025, pozdní sběr, polosuché","Hibernal 2025, výběr z hroznů, polosladké","Solaris 2024, výběr z hroznů, polosladké","Chardonnay 2024, výběr z hroznů, polosladké","Pálava 2025, výběr z hroznů, polosladké","Modrý Portugal 2022, pozdní sběr, suché","Frankovka 2021, výběr z hroznů, suché","Cabernet Sauvignon 2023, výběr z hroznů, suché","Merlot 2023, výběr z hroznů, suché","Merlot rosé 2025, pozdní sběr, polosuché","Brut sekt kvašený v lahvi","Brut sekt Charmat","Demi sekt Charmat","Demi sekt rosé Charmat"],fallback:{white:"K rybe a ľahkým jedlám je od Paulusovcov dobrý smer suchý Ryzlink vlašský 2024 alebo Sauvignon 2024; plnšie je Rulandské šedé 2025. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Cabernet Sauvignon 2023 alebo Merlot 2023, ľahší je Modrý Portugal 2022. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste polosladkú Pálavu 2025, Solaris 2024 alebo Demi sekt Charmat.",gift:"Na darček sa hodí Brut sekt kvašený v lahvi, polosladká Pálava 2025 alebo Cabernet Sauvignon 2023. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Paulus na konkrétne víno."}},
  mikulica:{brand:"Vinařství Mikulica",web:"https://www.vinarstvimikulica.cz/",products:["Veltlínské zelené 2025, suché","Ryzlink vlašský 2025, suché","Müller Thurgau 2024, suché","Sauvignon 2024, suché","Ryzlink rýnský 2024, suché","Chardonnay 2024, suché","Pálava 2025, polosuché","Rulandské šedé 2025, polosuché","#líbiFka 2025, polosladké","Sauvignon 2023, sladké (0,5 l)","Frankovka rosé 2023, suché","Frankovka 2023, suché","Rulandské modré 2023, suché","Merlot 2024, suché","Cuvée ze starého vinohradu 2022, suché (0,5 l)","Frizz víno rosé 2023, jemně perlivé, polosladké","Frizz víno Blanc 2024, jemně perlivé, polosuché","SEKT Riesling, BRUT"],fallback:{white:"K rybe a ľahkým jedlám je od Mikulicovcov dobrý smer suché Veltlínské zelené 2025 alebo Sauvignon 2024; plnší je Ryzlink rýnský 2024. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Merlot 2024 alebo Cuvée ze starého vinohradu 2022, ovocnejšia je Frankovka 2023. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste dezertný Sauvignon 2023, polosladkú #líbiFku 2025 alebo perlivé Frizz víno rosé.",gift:"Na darček sa hodí SEKT Riesling BRUT, Cuvée ze starého vinohradu 2022 alebo sladký Sauvignon 2023. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Mikulica na konkrétne víno."}},
  dubovskygrancic:{brand:"Vinárstvo Dubovský & Grančič",web:"https://dubovskygrancic.sk/",products:["Veltlínske zelené 2025, suché","Riesling 2024, suché","St. George Sylvaner 2024, suché","St. George 3 [O]SUDY 2024, suché","St. George Riesling Reserva 2024, suché","Pálava 2025, polosuché","Pesecká Leánka 2025, polosladké","Tramín červený 2024, sladké (0,5 l)","Veltlínske zelené 2016, hrozienkový výber (0,5 l)","Frankovka modrá 2023, suché","St. George Alibernet 2022, suché","St. George Dunaj 2023, suché","St. George Elisa I. 2023, suché","St. George Pinot Noir Zibich, suché","Nela rosé 2025, suché","St. George Cabernet Sauvignon rosé 2025, polosuché","SAMO SATO. rosé, pét-nat, suché","St. George Riesling Extra Brut sekt 2020"],fallback:{white:"K rybe a ľahkým jedlám je dobrý smer suchý Veltlínske zelené 2025 alebo Riesling 2024; plnší je St. George Riesling Reserva z dubových sudov. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam St. George Alibernet 2022 alebo Dunaj 2023, na každý deň Frankovku modrú 2023. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste sladký Tramín červený 2024, polosladkú Pesecká Leánku 2025 alebo vzácny hrozienkový výber Veltlínskeho zeleného 2016.",gift:"Na darček sa hodí St. George Elisa I. 2023, Pinot Noir Zibich alebo sekt Riesling Extra Brut. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinárstva Dubovský & Grančič na konkrétne víno."}},
  sabata:{brand:"Vinařství Šabata",web:"https://eshop.vinarstvisabata.cz/",products:["Sauvignon 2025, pozdní sběr - suché","Donauriesling 2025, pozdní sběr - suché","Savilon 2025, pozdní sběr - suché","Muškát moravský 2025, pozdní sběr - suché","Pálava 2025, pozdní sběr - suché","Rulandské šedé 2025, pozdní sběr - polosuché","Rulandské bílé - BATONNAGE 2022, pozdní sběr - suché","Pálava - BARRIQUE 2020, výběr z hroznů - suché","Tramín červený 2025, výběr z hroznů - polosladké","Pálava 2023, výběr z hroznů - sladké","Tramín červený 2013, LEDOVÉ VÍNO - sladké (0,375 l)","Merlot - BARRIQUE 2023, výběr z hroznů - suché","Rulandské modré - BARRIQUE 2018, výběr z hroznů - suché","Merlot ROSÉ 2025, pozdní sběr - polosladké","FRIZZANTE ROSÉ - Cuvée Mé Alibi 2024 - polosladké","SEKT Šabata BLANC 2018 - brut"],fallback:{white:"K rybe a ľahkým jedlám je od Šabatovcov dobrý smer suchý Sauvignon 2025 alebo Donauriesling 2025; plnšie je Rulandské bílé BATONNAGE 2022. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Merlot BARRIQUE 2023, pre výnimočnú príležitosť Rulandské modré BARRIQUE 2018. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste sladkú Pálavu 2023 so zlatými medailami, polosladký Tramín červený 2025 alebo ľadové víno z Tramínu.",gift:"Na darček sa hodí ľadové víno Tramín červený 2013, Rulandské modré BARRIQUE 2018 alebo SEKT Šabata BLANC. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Šabata na konkrétne víno."}},
  valka:{brand:"Vinařství Válka",web:"https://vinarstvivalka.cz/",products:["Veltlínské zelené 2023, suché, BIO","Ryzlink vlašský 2023, Terasy, suché, BIO","Chardonnay 2023, suché, BIO","Pálava 2025, suché, BIO","Ryzlink rýnský 2023, suché, BIO","Pálava oranžová 2024, suché, BIO","Bílá Frankovka 2024, polosuché, BIO","Cabernet Moravia rosé 2024, suché, BIO","La Guerre rosé 2022, suché, BIO","Nosislavský ryšák 2022, suché, BIO","Frankovka 2022, suché, BIO","Černý samet 2022, suché, BIO","Pinot Noir 2021/2022, suché, BIO, Family Reserve","Cabernet Sauvignon 2021, suché, BIO","Jantar z Výhonu 2020, polosuché, BIO","MuAu Pet-Nat 2025, brut natur, perlivé, BIO","BLAU Pet-Nat 2025, brut natur, perlivé, BIO"],fallback:{white:"K rybe a ľahkým jedlám je od Válkovcov dobrý smer suché Veltlínské zelené 2023 alebo Ryzlink vlašský Terasy; plnší je Ryzlink rýnský 2023 zo suda. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Černý samet 2022 alebo Cabernet Sauvignon 2021, ovocnejšia je Frankovka 2022. Výber vína ešte zohľadní vašu chuť.",sweet:"Válkovci robia hlavne suché BIO vína. Sladšie pôsobí dezertný Jantar z Výhonu v štýle sherry alebo polosuchá Bílá Frankovka 2024.",gift:"Na darček sa hodí Jantar z Výhonu, Pálava oranžová 2024 alebo Pinot Noir Family Reserve. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Válka na konkrétne víno."}},
  vican:{brand:"Vinařství Vican",web:"https://eshop.vican.wine/",products:["Sylvánské zelené 2025, pozdní sběr, suché","Sauvignon 2023, pozdní sběr, suché","Chardonnay 2023 - edice Karel Roden, suché","Ryzlink rýnský 2024, výběr z hroznů, suché","Tramín červený 2024, polosladké","Pálava 2024 - edice Karel Roden, polosladké","Ryzlink vlašský 2017, výběr z cibéb, sladké (0,25 l)","Rulandské modré 2024, suché","Merlot 2023 - Rodinná rezerva, suché","Frankovka 2022, Moravský akát, suché","Cuvée Jupiter 2022, suché","Cuvée Thé rosé 2022, polosuché","Cabernet Sauvignon ROSÉ 2025, polosladké","Frizzanté Muškát žlutý 2025, polosuché","Frizzanté Pálava 2025, polosladké"],fallback:{white:"K rybe a ľahkým jedlám je od Vicana dobrý smer suché Sylvánské zelené 2025 alebo Chardonnay 2023 z edície Karel Roden; plnší je Ryzlink rýnský 2024. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Frankovku 2022 alebo Cuvée Jupiter 2022, jemnejší je Merlot 2023 Rodinná rezerva. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste polosladkú Pálavu 2024 z edície Karel Roden, Tramín červený 2024 alebo sladký Ryzlink vlašský z cibéb.",gift:"Na darček sa hodí Cuvée Jupiter 2022, Pálava z edície Karel Roden alebo Frizzanté Pálava na prípitok. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Vican na konkrétne víno."}},
  jurasek:{brand:"Víno Jurášek",web:"https://vinojurasek.sk/",products:["Rizling rýnsky 2025, suché","Veltlínske zelené 2025, suché","Sauvignon blanc 2025, suché","Muškát moravský 2025, polosuché","Pálava 2024, sladké","Frizzante biele 2023, polosuché","Frizzante ružové 2023, polosuché","Cabernet Sauvignon rosé 2024, suché","Dornfelder 2024, suché","Alibernet 2021, suché","Pinot Noir Barrique 2020, suché"],fallback:{white:"K rybe a ľahkým jedlám je od Juráška dobrý smer suchý Rizling rýnsky 2025 alebo Sauvignon blanc 2025; na leto aj Cabernet Sauvignon rosé. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Pinot Noir Barrique 2020 alebo Alibernet 2021, ovocnejší je Dornfelder 2024. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste sladkú Pálavu 2024 alebo polosuchý Muškát moravský 2025.",gift:"Na darček sa hodí Pinot Noir Barrique 2020 alebo Frizzante ružové na prípitok. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Víno Jurášek na konkrétne víno."}},
  magula:{brand:"Vinárstvo Magula",web:"https://www.vinomagula.sk/",products:["Biely vlk 2023","Jungberg Devín 2023","Oranžový vlk 2023, oranžové víno","Ružový vlk 2022","Magula, Gabay, Bernheim: Sen 2020","Lupo! #1, šumivé víno","Carboniq 2023","Teufelstal Pinot noir 2022","Rosenberg Frankovka 2021","Červený vlk 2020","Baccara 2019","Teufelsecke Modrý Portugal 2017"],fallback:{white:"K rybe a ľahkým jedlám je od Magulu dobrý smer svieži Biely vlk 2023 alebo aromatický Jungberg Devín 2023; na leto aj Ružový vlk 2022. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam Rosenberg Frankovku 2021 alebo mohutného Červeného vlka 2020; ľahší a ovocný je Carboniq 2023. Výber vína ešte zohľadní vašu chuť.",sweet:"Magula robí suché vína; najovocnejšie a najjemnejšie sú Carboniq 2023 a Jungberg Devín 2023.",gift:"Na darček sa hodí Teufelsecke Modrý Portugal 2017 alebo rosé Sen 2020 z limitovanej série. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinárstva Magula na konkrétne víno."}},
  dobravinice:{brand:"Dobrá Vinice",web:"https://www.dobravinice.cz/",products:["Národní park 2021, cuvée, suché","Müller Thurgau 2022, suché","Veltlínské zelené 2021, suché","Májová Milerka 2021, suché","Ryzlink rýnský 2020 VOC, suché","Quatre Cuvée 2022, suché","Vlašský ryzlink Qvevri 2017, oranžové, suché","Pinot Noir Rubín 2018, suché","Frankovka Ibérico 2023, suché","Trois 2022, červené cuvée, suché","Crème de Kambrium 2022, pet-nat, suché","Crème de Riesling 2020, pet-nat, suché"],fallback:{white:"K rybe a ľahkým jedlám je z Dobrej Vinice dobrý smer cuvée Národní park 2021 alebo Veltlínské zelené 2021. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu odporúčam cuvée Trois 2022, ľahšia a ovocnejšia je Frankovka Ibérico 2023. Výber vína ešte zohľadní vašu chuť.",sweet:"Dobrá Vinice robí suché naturálne vína; ovocnejší a jemnejší je Müller Thurgau 2022 alebo Frankovka Ibérico 2023.",gift:"Na darček sa hodí Ryzlink rýnský 2020 VOC alebo oranžový Vlašský ryzlink Qvevri 2017. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Dobrej Vinice na konkrétne víno."}},
  skoupil:{brand:"Vinařství Skoupil",web:"https://eshop.skoupil.com/",products:["Ryzlink rýnský 2024, pozdní sběr, suché","Veltlínské zelené 2025, suché","Sauvignon 2025, polosuché","Pálava 2025, polosuché","Tramín červený 2024 Úlehle, suché","Frankovka 2023 Šmatláky, suché","Pinot Noir 2023 Frejúnky, suché","Merlot 2025, pozdní sběr, suché","ŠUM Sauvignon 2025, extra dry","Tramín Babiččine cibéby 2023 History, sladké, 0,5 l"],fallback:{white:"K rybe, hydine a ľahším jedlám je zo Skoupilu dobrý smer suchý Ryzlink rýnský 2024 alebo Veltlínské zelené 2025. Vo Výbere vína nájdem aj ďalšie.",red:"K mäsu a steaku odporúčam Frankovku 2023 Šmatláky z dubových sudov, jemnejší je Merlot 2025. Výber vína ešte zohľadní vašu chuť.",sweet:"Ak máte radi sladšie, skúste polosuchú Pálavu 2025 alebo sladký Tramín Babiččine cibéby k dezertom.",gift:"Na darček sa hodí Frankovka 2023 Šmatláky alebo šumivý ŠUM Sauvignon 2025. Vo Výbere vína zohľadníme, čo má obdarovaný rád.",default:"Ak neviete, kde začať, prejdite Výber vína. Štyri krátke otázky zúžia ponuku Vinařství Skoupil na konkrétne víno."}}
};

function cors(req,res){
  const origin=req.headers.origin||'';
  const ok=origin===''||/(^https:\/\/([a-z0-9-]+\.)?mojchatbot\.sk$)|(^https:\/\/.*\.vercel\.app$)|(^http:\/\/(localhost|127\.0\.0\.1):\d+$)/i.test(origin);
  res.setHeader('Access-Control-Allow-Origin',ok&&origin?origin:'https://mojchatbot.sk');
  res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');
}
function fallbackReply(demo,text){
  const q=String(text||'').toLocaleLowerCase('sk');
  if(/darč|darc/.test(q))return demo.fallback.gift;
  if(/sladk|dezert/.test(q))return demo.fallback.sweet;
  if(/červen|cerven|mäs|mas|steak|gril/.test(q))return demo.fallback.red;
  if(/biel|ryb|hydin|šalát|salat|ružov|ruzov|šumiv|sumiv|sekt/.test(q))return demo.fallback.white;
  return demo.fallback.default;
}
export default async function handler(req,res){
  cors(req,res);res.setHeader('Cache-Control','no-store');
  if(req.method==='OPTIONS')return res.status(204).end();
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
  let body={};try{body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});}catch{return res.status(400).json({error:'Invalid body'});}
  const demo=DEMOS[String(body.demoId||'')];if(!demo)return res.status(400).json({error:'Unknown demo'});
  const messages=(Array.isArray(body.messages)?body.messages:[]).filter(m=>m&&(m.role==='user'||m.role==='assistant')).slice(-10).map(m=>({role:m.role,content:String(m.content||'').slice(0,700)})).filter(m=>m.content.trim());
  const latest=messages.filter(m=>m.role==='user').at(-1)?.content||'';if(!latest)return res.status(400).json({error:'Missing user message'});
  const fallback=()=>res.status(200).json({reply:fallbackReply(demo,latest),fallback:true});
  if(!ANTHROPIC_API_KEY)return fallback();
  const system=[
    `Ste stručný poradca vo vinárstve ${demo.brand} a pomáhate vybrať víno z jeho e-shopu.`,
    'Odpovedajte jednoduchou slovenčinou, maximálne dvoma krátkymi vetami.',
    'Pomáhate s výberom podľa farby, chuti, príležitosti a jedla. Nepropagujte nadmerné pitie a neodporúčajte alkohol maloletým, tehotným ani vodičom.',
    'Odporučiť môžete iba presný názov vína zo zoznamu Overené vína. Nevymýšľajte ceny, ročníky, ocenenia ani chuťové tóny, ktoré nie sú uvedené.',
    `Oficiálny e-shop: ${demo.web}`,
    `Overené vína:\n- ${demo.products.join('\n- ')}`
  ].join('\n\n');
  try{
    const api=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:MODEL,max_tokens:160,temperature:0,system,messages})});
    if(!api.ok){console.error('wine Anthropic API error',api.status,await api.text());return fallback();}
    const data=await api.json();const reply=Array.isArray(data.content)?data.content.filter(b=>b.type==='text').map(b=>b.text).join('').trim():'';
    const clean=reply.replace(/[\u002a_\u0060#]/g,'').replace(/\s+/g,' ').trim();if(!clean)return fallback();
    return res.status(200).json({reply:clean});
  }catch(error){console.error('wine chat provider error',error);return fallback();}
}
