"""Compile one canonical catalogue for both browser and server; append demos."""
import json,re,sys,hashlib
from pathlib import Path
from net import save
ROOT=Path(__file__).resolve().parent.parent
META={
 'plantizia':dict(name='Plantizia',website='https://plantizia.sk/',currency='EUR',kinds=['plants','pots','substrates','terrariums'],theme=dict(brand='#035d30',accent='#035d30',soft='#eef3e9',paper='#fffefb',ink='#18271d',line='#d4dfd2'),categoryNotes={'plants':'Svetlo a starostlivosť','pots':'Rozmer a materiál','substrates':'Určenie a balenie','terrariums':'Hotové rastlinné kompozície'}),
 'gardenholice':dict(name='Garden Holice',website='https://www.gardenholice.sk/',currency='EUR',kinds=['plants','outdoor','pots','substrates'],kindLabels={'plants':'Domov a terasa'},theme=dict(brand='#393225',accent='#75613d',soft='#f4f0e6',paper='#fffefb',ink='#29251d',line='#dfd8c8'),categoryNotes={'plants':'Do interiéru a na letnú terasu','outdoor':'Kry, trvalky a okrasné trávy','pots':'Samostatné obaly a črepníky','substrates':'Zmesi podľa skupiny rastlín'}),
 'lukscheiter':dict(name='Lukscheiter',website='https://www.lukscheiter.eu/',currency='CZK',kinds=['plants','orchids','airplants','succulents'],theme=dict(brand='#184b29',accent='#7b287e',soft='#eef3e9',paper='#fffefb',ink='#18271d',line='#d5dfd3'),categoryNotes={'plants':'Izbové rastliny, hoye a bromélie','orchids':'Botanické druhy a kultivary','airplants':'Vzdušné rastliny','succulents':'Kaktusy, sukulenty a adéniá'})
}
ADDITIONS=json.loads((ROOT/'tools/shops.json').read_text()) if (ROOT/'tools/shops.json').exists() else {}
META.update({k:{x:v for x,v in b.items() if x in ['name','website','currency','kinds','kindLabels','theme','categoryNotes']} for k,b in ADDITIONS.items()})
for slug in sys.argv[1:]:
 source_path=sorted((ROOT/'research').glob(f'*/{slug}-products.json'))[-1]
 source=json.loads(source_path.read_text());products=[]
 for p in source:
  p['tags']=list(dict.fromkeys(p['tags']));p['facts']=list(dict.fromkeys(p['facts']))
  n={k:p.get(k) for k in ['id','name','kind','price','priceValue','currency','url','photo','tags','facts','reason','diameter','potDiameter','stock','checked','imageSource']}
  n['tags']=n['tags'][:];n['facts']=n['facts'][:]
  if n['kind']=='substrates':
   m=re.search(r'(\d+(?:[.,]\d+)?)\s*l\b',p['name'],re.I)
   if m:
    volume=float(m[1].replace(',','.'));tag='volume-small' if volume<=3 else 'volume-medium' if volume<=10 else 'volume-large';fact=f'Balenie podľa názvu: {volume:g} l.'
    if tag not in n['tags']:n['tags'].append(tag)
    if fact not in n['facts']:n['facts'].append(fact)
    n['reason']=' '.join(n['facts'][:3])
  if not (ROOT/n['photo'].lstrip('/')).exists():continue
  products.append(n)
 meta=META[slug].copy();meta.update(slug=slug,hero=f'/assets/plants/{slug}.jpg',mobileHero=f'/assets/plants/{slug}-mobile.jpg',logo=f'/assets/plants/{slug}-logo.png',mark=f'/assets/plants/{slug}-mark.png',products=products)
 meta['checked']=max(p['checked'] for p in products)
 meta['kinds']=[kind for kind in meta['kinds'] if any(p['kind']==kind for p in products)]
 (ROOT/'data').mkdir(exist_ok=True);save(ROOT/f'data/{slug}.json',meta)
 # Keep concise care evidence, with no bulk republishing of descriptions.
 for p in source:
  if p.get('sourceText'):p['descriptionSha256']=hashlib.sha256(p.pop('sourceText').encode()).hexdigest()
  else:p.pop('sourceText',None)
 save(source_path,source)
 print(slug,len(products),'published',flush=True)
brands={p.stem:json.loads(p.read_text()) for p in sorted((ROOT/'data').glob('*.json'))}
# Explicitly keep the first added brand as the landing-page default.
order=['plantizia','gardenholice','lukscheiter',*ADDITIONS];brands={k:brands[k] for k in order if k in brands}
catalog=json.dumps(brands,ensure_ascii=False,separators=(',',':'))
(ROOT/'catalog-data.mjs').write_text('/* Generated by tools/build.py; edit data sources, not this file. */\nexport const BRANDS='+catalog+';\n')
(ROOT/'nove-znacky-config.js').write_text('/* Generated by tools/build.py from data/*.json. */\nimport {BRANDS} from "./catalog-data.mjs";\nfor(const brand of Object.values(BRANDS)){brand.wordmark=`<img class="cx-logo" src="${brand.logo}" alt="${brand.name}">`;brand.launcherMark=brand.avatarMark=`<img class="cx-brand-mark" src="${brand.mark}" alt="">`;}\nwindow.COSMETICS_DEMOS={brands:BRANDS};\nawait import("./cosmetics.js");\n')
