const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const MODEL = process.env.CHAT_MODEL || 'claude-haiku-4-5';

const DEMOS = {
  mylo:{brand:'mylo',web:'https://www.mylo.sk/',products:['Hydratačný krém RUŽA A KONOPE','Pleťový olej AKO VÁNOK','Ceramidový krém s vitamínmi RADOSŤ','Hydratačné sérum INOVAŤ'],fallback:{dry:'Pri suchej alebo napnutej pleti je dobrý smer Hydratačný krém RUŽA A KONOPE. Krátky výber ešte zohľadní, či chcete krém, sérum alebo olej.',oily:'Pri vyššej tvorbe mazu sa pozrite na Pleťový olej AKO VÁNOK. Výber starostlivosti ešte zohľadní vašu hlavnú prioritu.',sensitive:'Pri citlivejšej pleti by som začal jemnejším smerom Ceramidový krém s vitamínmi RADOSŤ. Ak pleť výrazne alebo dlhodobo reaguje, vhodnosť kozmetiky konzultujte s odborníkom.',mature:'Ak chcete výživnejšiu starostlivosť, Ceramidový krém s vitamínmi RADOSŤ je rozumný smer. Výber potom zohľadní aj preferovanú textúru.',default:'Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku mylo na konkrétny produkt.'}},
  ponio:{brand:'ponio',web:'https://ponio.sk/',products:['Vanilka & kokos – pleťový krém','Healthy aging – pleťový krém','Lumina shield – denný ochranný pleťový krém','Ružová voda Hanus 250 ml'],fallback:{dry:'Pri suchej pleti je jednoduchý smer Vanilka & kokos – pleťový krém. Výber ešte zohľadní, či chcete iba jeden produkt alebo viac krokov.',oily:'Pri mastnejšej pleti odporúčam najprv zúžiť výber podľa priority a textúry. Poradca nebude hádať produkt, ktorý nemá pre tento profil dostatok podkladov.',sensitive:'Pri citlivejšej pleti je vhodné držať rutinu jednoduchú; ako doplnkový krok sa dá pozrieť na Ružová voda Hanus 250 ml. Pri výraznej reakcii pokožky je vhodná konzultácia s odborníkom.',mature:'Pre zrelšiu pleť je z ponuky jasný smer Healthy aging – pleťový krém. Výber ešte rozlíši, či chcete jednoduchú alebo kompletnú rutinu.',default:'Ak chcete jeden praktický denný produkt, pozrite Lumina shield – denný ochranný pleťový krém. Výber starostlivosti vie odporúčanie spresniť.'}},
  two:{brand:'two cosmetics',web:'https://www.twocosmetics.sk/',products:['Krém pre citlivú pleť','Krém pre suchú pleť','Krém pre problematickú pleť','Rutina pre zrelú pleť – PRO'],fallback:{dry:'Pri suchej pleti je priamy smer Krém pre suchú pleť. Výber starostlivosti ešte zohľadní, či chcete jeden produkt alebo celú rutinu.',oily:'Pri mastnejšej alebo problematickej pleti sa pozrite na Krém pre problematickú pleť. Výber potom doplní preferovaný rozsah rutiny.',sensitive:'Pri citlivejšej pleti je z ponuky najjasnejší smer Krém pre citlivú pleť. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.',mature:'Ak chcete komplexnejšiu starostlivosť o zrelú pleť, smeruje sem Rutina pre zrelú pleť – PRO. Pri jednoduchšom režime poradca zúži výber inak.',default:'two cosmetics má produkty rozdelené podľa potrieb pleti. Štyri krátke kroky vám pomôžu dostať sa ku konkrétnemu produktu bez filtrovania celého katalógu.'}},
  bellcoria:{brand:'Bellcoria',web:'https://bellcoria.sk/',products:['Organický opunciový olej','Elixír proti vráskam s bakuchiolom','Pleťový čistiaci gél','Prírodný ANTI-AGING komplex'],fallback:{dry:'Pri suchej pleti a preferencii oleja je jasný smer Organický opunciový olej. Výber ešte zohľadní, či hľadáte základ rutiny alebo cielený krok.',oily:'Pri mastnejšej pleti by som bez ďalších údajov nezačínal olejom naslepo. Výber starostlivosti najprv zúži prioritu a typ produktu.',sensitive:'Ak chcete jemný základ rutiny, pozrite Pleťový čistiaci gél. Pri výrazne reaktívnej pleti je vhodné zloženie konzultovať s odborníkom.',mature:'Pre zrelšiu pleť je cielený smer Elixír proti vráskam s bakuchiolom alebo Prírodný ANTI-AGING komplex podľa rozsahu rutiny. Výber pomôže rozhodnúť medzi jedným krokom a komplexnejšou starostlivosťou.',default:'Bellcoria má viac typov produktov, preto je najpraktickejší krátky Výber starostlivosti. Zohľadní pleť, prioritu, rozsah rutiny aj textúru.'}},
  biofy:{brand:'BIOFY',web:'https://biofy.sk/',products:['Hydratačný krém – suchá a citlivá pleť','Upokojujúci krém – problematická pleť','Výživný krém – normálna a zmiešaná pleť','Konopný krém – suchá a problematická pleť'],fallback:{dry:'Pri suchej alebo citlivejšej pleti je jasný smer Hydratačný krém – suchá a citlivá pleť. Výber ešte zohľadní vašu hlavnú prioritu.',oily:'Pri problematickej alebo mastnejšej pleti sa pozrite na Upokojujúci krém – problematická pleť. Poradca ešte zohľadní, či chcete jednoduchú alebo širšiu rutinu.',sensitive:'Pri citlivejšej pleti je z ponuky vhodný smer Hydratačný krém – suchá a citlivá pleť. Pri výraznej alebo opakovanej reakcii pokožky je vhodná konzultácia s odborníkom.',mature:'Ak nemáte výraznú citlivosť a hľadáte univerzálny krém, pozrite Výživný krém – normálna a zmiešaná pleť. Výber starostlivosti vie výsledok spresniť podľa vašich potrieb.',default:'BIOFY má krémy rozdelené podľa typu pleti. Výber starostlivosti vás cez štyri jednoduché kroky pošle na najrelevantnejší produkt.'}},
  anemone:{brand:'ANEMONE',web:'https://anemone.sk/',products:['Pleťový olej na zrelú pleť','Pleťový olej na normálnu & suchú pleť','Pleťový olej na mastnú & problematickú pleť','Kvetinová voda Ruža Damascénska'],fallback:{dry:'Pri suchej pleti je jasný smer Pleťový olej na normálnu & suchú pleť. Výber ešte zohľadní, či chcete iba jeden doplnok alebo širšiu rutinu.',oily:'Pri mastnejšej alebo problematickej pleti sa pozrite na Pleťový olej na mastnú & problematickú pleť. Krátky výber ešte spresní prioritu.',sensitive:'Ak chcete rutinu iba jemne doplniť, pozrite Kvetinová voda Ruža Damascénska. Pri výrazne reaktívnej pokožke je vhodné výber kozmetiky konzultovať s odborníkom.',mature:'Pre zrelšiu pleť je priamy smer Pleťový olej na zrelú pleť. Výber starostlivosti ešte zohľadní preferovanú rutinu.',default:'ANEMONE má viac jednoduchých olejových a doplnkových produktov. Výber starostlivosti pomôže rozhodnúť podľa typu pleti a priority.'}},
  modrapupava:{brand:"Modrá púpava",web:"https://www.modrapupava.sk/",products:["Inspiral Anti-age – krém na spevnenie pleti","Inspiral Energy – pleťové sérum","Problematická pleť – pleťový a telový olej","Fialka – pleťová olejová kúra"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Inspiral Anti-age – krém na spevnenie pleti. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Problematická pleť – pleťový a telový olej. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Fialka – pleťová olejová kúra. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Inspiral Anti-age – krém na spevnenie pleti. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Modrá púpava na konkrétny produkt."}},
  facederma:{brand:"Facederma",web:"https://facederma.sk/",products:["ANTI-AKNÉ krém pre problematickú pleť","Sérum kyseliny hyalurónovej","Liftingový krém na vrásky a kontúry tváre","Pleťový krém s hodvábom a kmeňovými bunkami"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Sérum kyseliny hyalurónovej. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na ANTI-AKNÉ krém pre problematickú pleť. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Pleťový krém s hodvábom a kmeňovými bunkami. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Liftingový krém na vrásky a kontúry tváre. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Facederma na konkrétny produkt."}},
  cyprianus:{brand:"Cyprianus",web:"https://www.cyprianus.sk/",products:["Hydratačný pleťový krém Mandľa a Malina 50 ml","Omladzujúci denný krém proti vráskam Q10 50 ml","Pleťové sérum Jojobový olej a ruža 50 ml","Hydratačný pleťový krém Pižmo a Bergamot 50 ml"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Hydratačný pleťový krém Mandľa a Malina 50 ml. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Hydratačný pleťový krém Pižmo a Bergamot 50 ml. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Pleťové sérum Jojobový olej a ruža 50 ml. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Omladzujúci denný krém proti vráskam Q10 50 ml. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Cyprianus na konkrétny produkt."}},
  panakeia:{brand:"Panakeia",web:"https://www.panakeia.sk/",products:["BÁTHORYČKA – nočný krém s dračou krvou 30 ml","BOSORKIN LEKTVAR – bakuchiol pleťové sérum 15 ml","Kopaničiarska žehlička s peptidom Argireline 20 ml","BÁTHORYČKA – čistiaca pleťová pena s dračou krvou 100 ml"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer BÁTHORYČKA – nočný krém s dračou krvou 30 ml. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na BÁTHORYČKA – čistiaca pleťová pena s dračou krvou 100 ml. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer BÁTHORYČKA – nočný krém s dračou krvou 30 ml. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer BOSORKIN LEKTVAR – bakuchiol pleťové sérum 15 ml. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Panakeia na konkrétny produkt."}},
  barboralori:{brand:"Barbora Lori",web:"https://www.barboralori.sk/",products:["Denný krém pre suchú a zrelšiu pleť s liftingovým účinkom","Opaľovací krém na tvár SPF 50 s nízkym komedogénnym indexom","Čistiace mlieko na tvár","Upokojujúce a hydratačné tonikum"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Denný krém pre suchú a zrelšiu pleť s liftingovým účinkom. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Opaľovací krém na tvár SPF 50 s nízkym komedogénnym indexom. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Čistiace mlieko na tvár. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Denný krém pre suchú a zrelšiu pleť s liftingovým účinkom. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Barbora Lori na konkrétny produkt."}},
  bellmedi:{brand:"BellMedi",web:"https://bellmedi.sk/",products:["Kyselina hyalurónová","Ibištekový olej","Kakaové maslo","Cédrová kvetová voda"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Kyselina hyalurónová. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Cédrová kvetová voda. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Kakaové maslo. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Ibištekový olej. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku BellMedi na konkrétny produkt."}},
  lavelin:{brand:"Lavelin",web:"https://www.lavelin.sk/",products:["Vyživujúci pleťový krém so šípkovým olejom","Pleťové sérum s bakuchiolom","Pleťový čistiaci gél s papájou a mangom","Malinové pleťové sérum s kyselinou hyalurónovou"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Vyživujúci pleťový krém so šípkovým olejom. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Pleťový čistiaci gél s papájou a mangom. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Vyživujúci pleťový krém so šípkovým olejom. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Pleťové sérum s bakuchiolom. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Lavelin na konkrétny produkt."}},
  kvitok:{brand:"Kvitok",web:"https://www.kvitok.sk/",products:["Konopný krém pre mastnú a problematickú pleť","Arganový krém pre zrelú pleť (30+) — denný","Pleťové sérum s kyselinou azelaovou","BB ochranný pleťový krém"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Arganový krém pre zrelú pleť (30+) — denný. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Konopný krém pre mastnú a problematickú pleť. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Pleťové sérum s kyselinou azelaovou. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Arganový krém pre zrelú pleť (30+) — denný. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Kvitok na konkrétny produkt."}},
  soaphoria:{brand:"Soaphoria",web:"https://www.soaphoria.sk/",products:["Osviežujúci čistiaci mousse na zmiešanú až mastnú pleť","Arganový olej","Levanduľa lekárska — organická kvetová voda","Herbaphoria — organická pleťová maska"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Arganový olej. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Osviežujúci čistiaci mousse na zmiešanú až mastnú pleť. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Levanduľa lekárska — organická kvetová voda. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Arganový olej. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Soaphoria na konkrétny produkt."}},
  syncare:{brand:"Syncare",web:"https://www.syncare.sk/",products:["GlycoRETINAL+C krém pre pleť so sklonom k akné","CENTELARIA upokojujúca maska pre citlivú pleť","BB NEW AGE omladzujúci denný krém SPF 20","Hydratačný gél s argánovým olejom a skvalánom"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer BB NEW AGE omladzujúci denný krém SPF 20. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na GlycoRETINAL+C krém pre pleť so sklonom k akné. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer CENTELARIA upokojujúca maska pre citlivú pleť. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer BB NEW AGE omladzujúci denný krém SPF 20. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Syncare na konkrétny produkt."}},
  fytopharma:{brand:"Fytopharma",web:"https://www.fytopharma.sk/",products:["Omladzujúci krém s kyselinou hyalurónovou","Pleťová voda s pH 4","Hydratačný krém s obsahom aminokyselín","Mastný krém s kakaovým maslom a vitamínom E"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Omladzujúci krém s kyselinou hyalurónovou. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Pleťová voda s pH 4. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Mastný krém s kakaovým maslom a vitamínom E. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Omladzujúci krém s kyselinou hyalurónovou. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Fytopharma na konkrétny produkt."}},
  natureal:{brand:"Natureal",web:"https://eshop.natureal.sk/sk/",products:["MEDI-PEEL Bor-Tox Cream — antiage krém","HARUHARU WONDER Black Bamboo Mist — pleťová hmla","OSKIA Universal Hyaluronic Acid Serum","THE ORDINARY AHA 30% + BHA 2% Peeling Solution"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer MEDI-PEEL Bor-Tox Cream — antiage krém. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na THE ORDINARY AHA 30% + BHA 2% Peeling Solution. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer HARUHARU WONDER Black Bamboo Mist — pleťová hmla. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer MEDI-PEEL Bor-Tox Cream — antiage krém. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Natureal na konkrétny produkt."}},
  dulcia:{brand:"Dulcia",web:"https://www.dulcia.sk/",products:["Výživný pleťový krém s lipidmi","Pleťový krém na akné – čistiaci komplex","Nočné mikrobiotické pleťové sérum – Upokojujúce","Sérum proti vráskam s kyselinou hyalurónovou","Ľahký hydratačný krém","Bioaktívne olejové sérum"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Výživný pleťový krém s lipidmi. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Pleťový krém na akné – čistiaci komplex. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Nočné mikrobiotické pleťové sérum – Upokojujúce. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Sérum proti vráskam s kyselinou hyalurónovou. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Dulcia na konkrétny produkt."}},
  yemna:{brand:"Yemna",web:"https://www.yemna.sk/",products:["Slivka & Ibištek pleťový krém","INTENSE CLARIFYING rozjasňujúca emulzia 30 ml","CICA Micro repair cream 50 ml","AVEQ10 hydratačný pleťový krém proti vráskam 50 ml","Moruša výživný pleťový krém 50 ml","Omladenie s Q10 a bakuchiolom – pleťový olej 30 ml","Obnova pleťové tonikum s niacínom"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer Slivka & Ibištek pleťový krém. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu a stopách po nedokonalostiach sa pozrite na INTENSE CLARIFYING rozjasňujúcu emulziu. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer CICA Micro repair cream. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer Moruša výživný pleťový krém. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku Yemna na konkrétny produkt."}},
  namy:{brand:"NAMY",web:"https://www.namy.sk/",products:["NI + HA + E pleťový krém s niacínamidom","Akné hydrogel – gélové sérum 30 ml","Dermal Sensitive – krém na citlivú pokožku 50 ml","HYALURON – pleťové sérum s kyselinou hyalurónovou","LIFT + FILL pleťový krém s liftingovým efektom","BAKUCHIOL – olejové pleťové sérum s 1 % bakuchiolom","HYDRA – gélová hydratačná esencia"],fallback:{dry:"Pri suchej alebo napnutej pleti je dobrý smer HYALURON – pleťové sérum s kyselinou hyalurónovou pod krém NI + HA + E. Výber starostlivosti ešte zohľadní, či chcete krém, sérum alebo olej.",oily:"Pri vyššej tvorbe mazu sa pozrite na Akné hydrogel – gélové sérum. Výber ešte spresní vašu hlavnú prioritu.",sensitive:"Pri citlivejšej pleti je z ponuky vhodný smer Dermal Sensitive – krém na citlivú pokožku. Ak pokožka výrazne alebo dlhodobo reaguje, konzultujte starostlivosť s odborníkom.",mature:"Pre zrelšiu pleť je priamy smer LIFT + FILL pleťový krém s liftingovým efektom. Výber starostlivosti ešte zohľadní, ako komplexnú rutinu chcete.",default:"Ak neviete, kde začať, prejdite Výber starostlivosti. Štyri krátke kroky zúžia ponuku NAMY na konkrétny produkt."}}
};

function cors(req,res){
  const origin=req.headers.origin||'';
  const ok=origin===''||/(^https:\/\/([a-z0-9-]+\.)?mojchatbot\.sk$)|(^https:\/\/.*\.vercel\.app$)|(^http:\/\/(localhost|127\.0\.0\.1):\d+$)/i.test(origin);
  res.setHeader('Access-Control-Allow-Origin',ok&&origin?origin:'https://mojchatbot.sk');
  res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','POST, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type');
}
function fallbackReply(demo,text){
  const q=String(text||'').toLocaleLowerCase('sk');
  if(/such|pnut|dehyd/.test(q))return demo.fallback.dry;
  if(/mast|lesk|nedokonal|problem|akné/.test(q))return demo.fallback.oily;
  if(/citliv|reakt|podráž|štíp/.test(q))return demo.fallback.sensitive;
  if(/zrel|vrásk|pruž/.test(q))return demo.fallback.mature;
  return demo.fallback.default;
}
export default async function handler(req,res){
  cors(req,res);res.setHeader('Cache-Control','no-store');
  if(req.method==='OPTIONS')return res.status(204).end();
  if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});
  let body={};try{body=typeof req.body==='string'?JSON.parse(req.body):(req.body||{});}catch{return res.status(400).json({error:'Invalid body'});}
  const demo=DEMOS[String(body.demoId||'')];if(!demo)return res.status(400).json({error:'Unknown demo'});
  const messages=(Array.isArray(body.messages)?body.messages:[]).filter(m=>m&&(m.role==='user'||m.role==='assistant')).slice(-10).map(m=>({role:m.role,content:String(m.content||'').slice(0,700)})).filter(m=>m.content.trim());
  const latest=messages.filter(m=>m.role==='user').at(-1)?.content||'';if(!latest)return res.status(400).json({error:'Missing user message'});
  const fallback=()=>res.status(200).json({reply:fallbackReply(demo,latest),fallback:true});
  if(!ANTHROPIC_API_KEY)return fallback();
  const system=[
    `Ste stručný produktový poradca pre kozmetický e-shop ${demo.brand}.`,
    'Odpovedajte jednoduchou slovenčinou, maximálne dvoma krátkymi vetami.',
    'Pomáhate s orientačným kozmetickým výberom podľa preferencií. Nerobte zdravotnú diagnózu, nesľubujte liečbu a nevymýšľajte medicínske tvrdenia.',
    'Odporučiť môžete iba presný názov produktu zo zoznamu Overené produkty. Nevymýšľajte ceny, zloženie ani účinky, ktoré nie sú uvedené.',
    'Pri výraznom, bolestivom alebo dlhodobom kožnom probléme odporučte konzultáciu s dermatológom alebo iným odborníkom.',
    `Oficiálny e-shop: ${demo.web}`,
    `Overené produkty:\n- ${demo.products.join('\n- ')}`
  ].join('\n\n');
  try{
    const api=await fetch('https://api.anthropic.com/v1/messages',{method:'POST',headers:{'content-type':'application/json','x-api-key':ANTHROPIC_API_KEY,'anthropic-version':'2023-06-01'},body:JSON.stringify({model:MODEL,max_tokens:160,temperature:0,system,messages})});
    if(!api.ok){console.error('cosmetics Anthropic API error',api.status,await api.text());return fallback();}
    const data=await api.json();const reply=Array.isArray(data.content)?data.content.filter(b=>b.type==='text').map(b=>b.text).join('').trim():'';
    const clean=reply.replace(/[\u002a_\u0060#]/g,'').replace(/\s+/g,' ').trim();if(!clean)return fallback();
    return res.status(200).json({reply:clean});
  }catch(error){console.error('cosmetics chat provider error',error);return fallback();}
}
